spring.application.name=LifeSure-Insuarnce-Management-System

# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/branch_man
spring.datasource.username=workbench
spring.datasource.password=win10love

# Create tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8082

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
