spring.application.name=LifeSure-Insurance-Management-System

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/SecureLife
spring.datasource.username=workbench
spring.datasource.password=win10love
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Allow file uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#  Serve static files from uploads directory
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# If using Spring Boot 3+, also add:
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

